import WeilKernelOnset.PartialReflection
import WeilKernelOnset.TwoMetric
import WeilKernelOnset.CompactStrong
import WeilKernelOnset.StripRestriction
import WeilKernelOnset.CompactLocalization
import WeilKernelOnset.KernelResponse
import WeilKernelOnset.LogScale
import WeilKernelOnset.BoundaryProfile
import WeilKernelOnset.BoundaryCorrelation
import WeilKernelOnset.LogBoundary
import WeilKernelOnset.Onset
import WeilKernelOnset.Assembly

import WeilKernelOnset.PositiveRemainder
import WeilKernelOnset.MixedOnset
import WeilKernelOnset.RelativeOnset
import WeilKernelOnset.RelativeAssembly
